version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-theme-blog
    versions:
    - 2.0.5
    - 2.0.6
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.1
    - 2.32.10
    - 2.32.11
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.6
    - 2.32.8
    - 2.32.9
